### ISSUE TITLE
Using JIVE in AudioProcessorEditor

### ISSUE THREAD

**Issue by jurihock** [ImJimmi/JIVE#129]
Hi James,

your example shows an `juce::JUCEApplication`.

Is there a way to embed JIVE in an `juce::AudioProcessorEditor`?

**Comment by ImJimmi** [comment]
Right now the easiest approach would be to create a `juce::AudioProcessorEditor` as normal and then use JIVE within the editor to create the UI. E.g. something like:

```cpp
class Editor : public juce::AudioProcessorEditor
{
public:
    Editor(juce::AudioProcessor& p)
        : juce::AudioProcessorEditor{ p }
    {
        jive::Interpreter interpreter;
        view = interpreter.interpret(juce::ValueTree{"Component", {...}});

        addAndMakeVisible(*view->getComponent());
        setSize(view->getComponent()->getWidth(),
                view->getComponent()->getHeight());
    }

private:
    std::unique_ptr<jive::GuiItem> view;
};
```

I'm working on some stuff to make this nicer so you can use JIVE to create the `juce::AudioProcessorEditor` itself however this is proving tricky due to ownership issues as `juce::AudioProcessor::createEditor()` needs to return a unique owning pointer whereas `jive::GuiItem`s wrap their corresponding `juce::Component`s using shared pointers.

I'll leave this open until I have a proposed solution.

**Comment by jurihock** [comment]
Thanks for the example, I'll definitely try it out.

By the way, merry Christmas!
