### ISSUE TITLE
github discussions section

### ISSUE THREAD

**Issue by mightgoyardstill** [ImJimmi/JIVE#138]
could i request a github discussions section so i can ask silly "how can i do this" questions?

**Comment by ImJimmi** [comment]
I wouldn't be against this if it would work best for you, but I'd prefer to keep the number of channels of communication to a minimum if possible. Otherwise it makes it more difficult for me to keep on top of things, and makes it difficult for others to know where to look for answers.

My preference would be to use this thread on the JUCE forums for these sorts of discussions: https://forum.juce.com/t/introducing-jive-the-ultimate-juce-extension-for-building-guis/56534

Would that work for you?

**Comment by mightgoyardstill** [comment]
yeah thats fine! wasn't too sure what the best form of communication would be so appreciate you clearing that up
